version: '3'
services:
  api:
    container_name: 'recipes-api'
    build: .
    ports:
      - '3000:3000'
  db:
    container_name: 'recipes-mongo'
    image: 'mongo'
    ports: 
      - '27017:27017'
