version: '3'
services:
  api:
    container_name: 'recipes-api'
    build: .
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://recipes-mongo:27017
      - MONGO_DB_NAME=recipes
      - JWT_SIGN_PASSWORD=password
      # In docker-compose.override.yml to set.
      # - GITHUB_CLIENT_SECRET=*****
  db:
    container_name: 'recipes-mongo'
    image: 'mongo'
    ports: 
      - '27017:27017'
